apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbbouncer.fullname" . }}-config
  labels:
    {{- include "dbbouncer.labels" . | nindent 4 }}
data:
  dbbouncer.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
