{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dbbouncer.fullname" . }}
  labels:
    {{- include "dbbouncer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "dbbouncer.selectorLabels" . | nindent 6 }}
{{- end }}
