apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbbouncer.fullname" . }}
  labels:
    {{- include "dbbouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.postgresPort }}
      targetPort: postgres
      protocol: TCP
    - name: mysql
      port: {{ .Values.service.mysqlPort }}
      targetPort: mysql
      protocol: TCP
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "dbbouncer.selectorLabels" . | nindent 4 }}
