{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dbbouncer.fullname" . }}
  labels:
    {{- include "dbbouncer.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "dbbouncer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
